### ISSUE TITLE
inheritance callback chain

### ISSUE THREAD

**Issue by lime-green** [fbonetti/method_hooks#3]
Hey there, right now the spec states: `expect(grandchild.events).to eq(['parent before', 'child before', 'grandchild before', 'save'])`

I think it makes more sense for the child callbacks to be triggered first then chain up. Then the spec would be: `expect(grandchild.events).to eq(['grandchild before', 'child before', 'parent before', 'save'])`

Do you agree?

**Comment by lime-green** [comment]
I submitted a pull request for this issue. It's a little verbose, maybe you know a more elegant way :)
https://github.com/fbonetti/method_hooks/pull/4

I also took the liberty of removing the active support subclasses stuff since I'm pretty sure that didn't do anything.

**Comment by fbonetti** [comment]
@lime-green Thanks again for contributing to this project! I think it's more intuitive for callbacks to be called in the order they were created, regardless of inheritance. For example:

``` ruby
Parent.before(:save) { puts 'first parent before' }
Child.before(:save) { puts 'child before' }
Parent.before(:save) { puts 'second parent before' }
```

I would expect the output of `Child.new.save` to be:

``` ruby
# first parent before
# child before
# second parent before
```

This behavior is also consistent with the way Rails handles callbacks.

The purpose of the subclasses stuff is to ensure that callbacks added the parent class correctly propagate to all of its ancestors.

**Comment by lime-green** [comment]
Oh cool! I wasn't aware that Rails did it this way. Thanks for the info :D 
I'll close my PR
